package net.haustov.hobgoblin.data;
// Generated Mar 15, 2012 12:36:19 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Purchase generated by hbm2java
 */
public class Purchase  implements java.io.Serializable {


     private int idpurchase;
     private Product product;
     private User user;
     private Order order;
     private Integer idorder;
     private BigDecimal amount;
     private Date date;

    public Purchase() {
    }

	
    public Purchase(int idpurchase, Product product, User user, Order order) {
        this.idpurchase = idpurchase;
        this.product = product;
        this.user = user;
        this.order = order;
    }
    public Purchase(int idpurchase, Product product, User user, Order order, Integer idorder, BigDecimal amount, Date date) {
       this.idpurchase = idpurchase;
       this.product = product;
       this.user = user;
       this.order = order;
       this.idorder = idorder;
       this.amount = amount;
       this.date = date;
    }
   
    public int getIdpurchase() {
        return this.idpurchase;
    }
    
    public void setIdpurchase(int idpurchase) {
        this.idpurchase = idpurchase;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Order getOrder() {
        return this.order;
    }
    
    public void setOrder(Order order) {
        this.order = order;
    }
    public Integer getIdorder() {
        return this.idorder;
    }
    
    public void setIdorder(Integer idorder) {
        this.idorder = idorder;
    }
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


