package net.haustov.hobgoblin.data;
// Generated Mar 15, 2012 12:36:19 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Store generated by hbm2java
 */
public class Store  implements java.io.Serializable {


     private int idstore;
     private Product product;
     private User user;
     private BigDecimal amount;
     private Date date;

    public Store() {
    }

    public Store(int idstore, Product product, User user, BigDecimal amount, Date date) {
       this.idstore = idstore;
       this.product = product;
       this.user = user;
       this.amount = amount;
       this.date = date;
    }
   
    public int getIdstore() {
        return this.idstore;
    }
    
    public void setIdstore(int idstore) {
        this.idstore = idstore;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


