package net.haustov.hobgoblin.data;
// Generated Mar 15, 2012 12:36:19 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Units generated by hbm2java
 */
public class Units  implements java.io.Serializable {


     private Integer idunits;
     private String name;
     private Set products = new HashSet(0);

    public Units() {
    }

    public Units(String name, Set products) {
       this.name = name;
       this.products = products;
    }
   
    public Integer getIdunits() {
        return this.idunits;
    }
    
    public void setIdunits(Integer idunits) {
        this.idunits = idunits;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getProducts() {
        return this.products;
    }
    
    public void setProducts(Set products) {
        this.products = products;
    }




}


